RDKB-3972 : Fix build issue
Reason for change:  undefined reference to `log_debug, replace log_debug with snooper_dbg
Test Procedure: Need to validate arris xb3 yocto build
Risks: low

Change-Id: I5b31940f4f8e6a713b15afbb489e68e69348ac3a
Signed-off-by: rthangamani <ramakrishnan.thangamani@wipro.com>