RDKCOM-2899: REFPLTB-1602 : observing build errors for ccsp-hotspot componen...
Reason for change: Observing below error on 64bit architecture
cosa_hotspot_dml.c:125:25: error: format '%d' expects argument of type 'int', but argument 4 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
|   125 |         CcspTraceError(("Invalid Client MAC address length %d, expected %zu\n", strlen(ret), sizeof(l_cMacAddr)));
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~
Test Procedure: build should be success on both 64bit and 32bit arch
Risks: Low
Signed-off-by: kpandu549 <keerthana_pandurangan@comcast.com>

(cherry picked from commit e5b1f0ab72db2a7914d237a3360164a0c23b7d1c)
Change-Id: I8a7b955319c7ef09a2f90a6b9507e291d4f8b6e7